### ISSUE TITLE
CSSStyleSheet.insertRule?

### ISSUE THREAD

**Issue by rtsao** [jxnblk/cxs#1]
Hi there, very cool project! 😄 

I was just curious what your reasoning was for using `insertRule` over something like:

```js
styleTag.appendChild(document.createTextNode(css))
```

I'm guessing `insertRule` probably has better performance (maybe?), but one possible downside I've noticed is it looks like the styles contained in the stylesheet aren't visible when inspecting the style element.

**Comment by jxnblk** [comment]
Thanks! The current implementation is pretty rough, but I'm using `insertRule` with the assumption that that might make stylesheets easier to diff and only patch updates, rather than rewriting the whole thing each render cycle. Will definitely need to do some perf tests on all this.

As far as the CSS not showing as a text node in the style tag, I don't really find looking at minified CSS that helpful in general. What is the use case for being able to see that?
